### ISSUE TITLE
Not compatible with most recent version of AltStore (1.7)

### ISSUE THREAD

**Issue by ammacdonald3** [Balackburn/Apollo#13]
I have AltServer 1.7.1 and AltStore 1.7 installed. When attempting to install Apollo from the link on this repo, AltStore on my iPhone errors with: The source "Apollo for Reddit" is not supported by this version of AltStore.

**Comment by Balackburn** [comment]
Hello, it's because Altstore doesn't accept external sources on the normal version you need to use the beta version, nothing to do with my repo, you can't add any repo except the trusted ones.

Use SideStore instead : https://sidestore.io/

Or

Use Altstore 2.0 beta from here : https://cdn.altstore.io/file/altstore/apps/altstore/2_0_b7.ipa
